WebShop/Controllers/PageContentController.cs
using BLL;
using Model.Base;
using Model.ViewModels.PageContent;
using System.Web;
using System.Web.Mvc;

namespace WebShop.Controllers
{
    public class PageContentController : BaseController
    {
        // GET: PageContent
        public ActionResult Index()
        {
            return View();
        }

        // GET: PageContent/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PageContent/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PageContent/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [ActionName("gfpc")]
        public IHtmlString GetFirstPageContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(1);

            return MvcHtmlString.Create(vmPageContent.Content);

        }

        [ActionName("gfc")]
        public IHtmlString GetFooterContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(2);

            return MvcHtmlString.Create(vmPageContent.Content);

        }

        [ActionName("lfpcf")]
        public ActionResult LoadFirstPageContentForm()
        {
            return View("FirstPageContent", new VmPageContent
            {
                Id = 1,
                FormTitle = "Edit first page content"
            });
        }

        [ActionName("lacf")]
        public ActionResult LoadAboutContentForm()
        {
            return View("AboutContent", new VmPageContent
            {
                Id = 5,
                FormTitle = new BaseViewModel()["در باره ما"],
               
            });
        }

        [ActionName("gahcbcl")]
        public JsonResult GetAboutHtmlContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(5);

            vmPageContent.FormTitle = new BaseViewModel()["در باره ما"];

            var jsonData = new
            {
                vmPageContent.Subject,
                vmPageContent.Content,
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);

        }

        [ActionName("gahcbl")]
        public JsonResult GetAboutHtmlContentByLanguage(int id)
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByLanguageId(5, id);

            vmPageContent.FormTitle = new BaseViewModel()["در باره ما"];

            var jsonData = new
            {
                vmPageContent.Subject,
                vmPageContent.Content,
                vmPageContent.Type,
                vmPageContent.Id,
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);

        }

        [ActionName("gac")]
        public IHtmlString GetAboutContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(5);

            return MvcHtmlString.Create(vmPageContent.Subject + vmPageContent.Content);

        }
        [ActionName("lapcf")]
        public ActionResult LoadAboutPublisherContentForm()
        {
            return View("AboutPublisherContent", new VmPageContent
            {
                Id = 6,
                FormTitle = "Edit about publisher content"
            });
        }

        [ActionName("gaphc")]
        public JsonResult GetAboutPublisherHtmlContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(6);

            vmPageContent.FormTitle = "Edit about content";

            return Json(vmPageContent.Content, JsonRequestBehavior.AllowGet);

        }

        [ActionName("gapc")]
        public IHtmlString GetAboutPublisherContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(6);

            return MvcHtmlString.Create(vmPageContent.Content);

        }

        [ActionName("lfcf")]
        public ActionResult LoadFooterContentForm()
        {


            return View("FooterContent", new VmPageContent
            {
                Id = 2,
                FormTitle = "Edit footer content"
            });
        }


        [ActionName("gfphc")]
        public JsonResult GetFirstPageHtmlContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(1);

            vmPageContent.FormTitle = "Edit first page content";

            return Json(vmPageContent.Content, JsonRequestBehavior.AllowGet);

        }

        [ActionName("gfhc")]
        public JsonResult GetFooterHtmlContent()
        {
            var blPageContent = new BLPageContent(CurrentLanguageId);
            var vmPageContent = blPageContent.GetByCurrentLanguageId(2);

            vmPageContent.FormTitle = "Edit footer content";

            return Json(vmPageContent.Content, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [ActionName("sfpc")]
        public ActionResult SaveFirstPageContent(VmPageContent model)
        {
            try
            {
                var blPageContent = new BLPageContent(CurrentLanguageId);
                blPageContent.UpdatePageContent(model);

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ActionName("sac")]
        public ActionResult SaveAboutContent(VmPageContent model)
        {
            try
            {
                var blPageContent = new BLPageContent(CurrentLanguageId);
                blPageContent.UpdatePageContent(model);

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ActionName("sapc")]
        public ActionResult SaveAboutPublisherContent(VmPageContent model)
        {
            try
            {
                var blPageContent = new BLPageContent(CurrentLanguageId);
                blPageContent.UpdatePageContent(model);

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ActionName("sfc")]
        public ActionResult SaveFooterContent(VmPageContent model)
        {
            try
            {
                var blPageContent = new BLPageContent(CurrentLanguageId);
                blPageContent.UpdatePageContent(model);

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: PageContent/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PageContent/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShop/Views/PageContent/AboutContent.cshtml
@using Model.ToolsModels.DropDownList
@model Model.ViewModels.PageContent.VmPageContent

@{
    ViewBag.Tile = Model["About Content Content"];
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-12">
    
    @Html.Label(Model["زبان"], htmlAttributes: new { @class = "control-label col-sm-1 col-12  col-md-1" })

    <div class="col-12 col-sm-4 col-md-4">

        @Html.Partial("_DropDownList", new VmDropDownList
        {
            HtmlElementId = "languageId",
            DataController = "admin",
            DataAction = "galddl",
            OptionLabel = Model["انتخاب زبان ..."],
            ActiveItemValue = Model.CurrentLanguageId.ToString(),
            OnItemSelected = "JournalDropDownList_OnClientSelectedItem",

        })

        <script>
            function JournalDropDownList_OnClientSelectedItem(id)
            {
                loadFirstPageContent(id);
            }
        </script>

    </div>

    <hr />

</div>

<div class="col-12">
    @using (Html.BeginForm("sac", "PageContent", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="row text-center">
            <h2>
                @Model["متن خلاصه"]
            </h2>
        </div>
        <div id="HTMLSubject" name="Subject"></div>
        <div class="row text-center">
            <h2>
                @Model["متن کامل"]
            </h2>


        </div>
        <div id="HTMLContent" name="Content"></div>

        <input type="hidden" id="idHidden" name="Id" value="@Model.Id" />
        <input type="hidden" id="typeHidden" name="Type" value="@Model.Type" />

        <div class="form-group">
            <div class="col-md-offset-3 col-md-8">
                <button id="saveButton" type="button" class="btn btn-primary">

                    <span class="">@Model["ذخیره"]</span>

                </button>
                <a href="/Admin/Index" class="btn btn-primary">
                    <span class="">@Model["انصراف"]</span>
                </a>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {

        $("#saveButton").click(function () {
            $.ajax({
                type: "POST",
                url: "/PageContent/sac",
                data: {
                    Id: $("#idHidden").val(),
                    Type: $("#typeHidden").val(),
                    Content: $("#HTMLContent").summernote('code'),
                    Subject: $("#HTMLSubject").summernote('code'),
                    LanguageId: $("#languageId").val(),
                },
                success: function (response) {
                    window.location.href = '/home';
                },
                error: function (data, textStatus, XMLHttpRequest) {
                }
            });
        });

        $("#HTMLContent").summernote({
            height: 300, minHeight: null, maxHeight: null, focus: false,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']], ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'hr', 'uploadfile']],
                ['view', ['fullscreen', 'codeview']],
                ['help', ['help']]
            ],
        });

        $("#HTMLSubject").summernote({
            height: 300, minHeight: null, maxHeight: null, focus: false,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']], ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'hr', 'uploadfile']],
                ['view', ['fullscreen', 'codeview']],
                ['help', ['help']]
            ],
        });

  
    });
    function loadFirstPageContent(languageId) {
        $.ajax({
            type: "POST",
            url: "/PageContent/gahcbl/" + languageId,
            success: function (response) {

                $("#HTMLSubject").summernote('code', response.Subject);
                $("#HTMLContent").summernote('code', response.Content);
                $("#typeHidden").val(response.Type);
                $("#idHidden").val(response.Id);
            },
            error: function (data, textStatus, XMLHttpRequest) {

            }
        });
    }
</script>

WebShop/Views/PageContent/AboutPublisherContent.cshtml
@model Model.ViewModels.PageContent.VmPageContent

@{
    ViewBag.Tile = Model["About Publisher Content Content"];
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-12">


    @using (Html.BeginForm("sapc", "PageContent", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>@Model.FormTitle.</h4>

        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div id="HTMLContent" name="Content"></div>

        <input type="hidden" id="idHidden" name="Id" value="@Model.Id" />

        <div class="form-group">
            <div class="col-md-offset-3 col-md-8">
                <button id="saveButton" type="button" class="btn btn-primary">

                    <span class="">@Model["Save"]</span>
                </button>
                <a href="/Admin/Index" class="btn btn-primary">
                    <span class="">@Model["Cancel"]</span>
                </a>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        $("#saveButton").click(function () {

            $.ajax({
                type: "POST",
                url: "/PageContent/sapc",
                data: { Id: $("#idHidden").val(), Content: $("#HTMLContent").summernote('code')},
                success: function (response) {
                    window.location.href = '/home';
                },
                error: function (data, textStatus, XMLHttpRequest) {
                }
            });
        });

        $("#HTMLContent").summernote({
            height: 300, minHeight: null, maxHeight: null, focus: false,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']], ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'hr', 'uploadfile']],
                ['view', ['fullscreen', 'codeview']],
                ['help', ['help']]
            ],
        });


        $.ajax({
            type: "POST",
            url: "/PageContent/gaphc",
            success: function (response) {

                $("#HTMLContent").summernote('code',  response);
            },
            error: function (data, textStatus, XMLHttpRequest) {

            }
        });

    });
</script>

WebShop/Views/PageContent/FirstPageContent.cshtml
@model Model.ViewModels.PageContent.VmPageContent

@{
    ViewBag.Tile = Model["Home Page Content"];
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="col-12">


    @using (Html.BeginForm("sfpc", "PageContent", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>@Model.FormTitle.</h4>

        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div id="HTMLContent" name="Content"></div>

        <input type="hidden" id="idHidden" name="Id" value="@Model.Id" />

        <div class="form-group">
            <div class="col-md-offset-3 col-md-8">
                <button id="saveButton" type="button" class="btn btn-primary">

                    <span class="">@Model["Save"]</span>
                </button>
                <a href="/Admin/Index" class="btn btn-primary">
                    <span class="">@Model["Cancel"]</span>
                </a>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        $("#saveButton").click(function () {

            $.ajax({
                type: "POST",
                url: "/PageContent/sfpc",
                data: { Id: $("#idHidden").val(), Content: $("#HTMLContent").summernote('code')},
                success: function (response) {
                    window.location.href = '/home';
                },
                error: function (data, textStatus, XMLHttpRequest) {
                }
            });
        });

        $("#HTMLContent").summernote({
            height: 300, minHeight: null, maxHeight: null, focus: false,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']], ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'hr', 'uploadfile']],
                ['view', ['fullscreen', 'codeview']],
                ['help', ['help']]
            ],
        });


        $.ajax({
            type: "POST",
            url: "/PageContent/gfphc",
            success: function (response) {

                $("#HTMLContent").summernote('code',  response);
            },
            error: function (data, textStatus, XMLHttpRequest) {

            }
        });

    });
</script>

WebShop/Views/PageContent/FooterContent.cshtml
@model Model.ViewModels.PageContent.VmPageContent
@{
    ViewBag.Title = Model["Footer Content"];
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="col-12">

    @using (Html.BeginForm("sfc", "PageContent", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>@Model.FormTitle.</h4>

        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div id="HTMLContent" name="Content"></div>

        <input type="hidden" id="idHidden" name="Id" value="@Model.Id" />

        <div class="form-group">
            <div class="col-md-offset-3 col-md-8">
                <button id="saveButton" type="button" class="btn btn-primary">

                    <span class="">@Model["Save"]</span>
                </button>
                <a href="/Admin/Index" class="btn btn-primary">
                    <span class="">@Model["Cancel"]</span>
                </a>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        $("#saveButton").click(function () {

            $.ajax({
                type: "POST",
                url: "/PageContent/sfc",
                data: { Id: $("#idHidden").val(), Content: $("#HTMLContent").summernote('code')},
                success: function (response) {
                    window.location.href = '/home';
                },
                error: function (data, textStatus, XMLHttpRequest) {
                }
            });
        });

        $("#HTMLContent").summernote({
            height: 300, minHeight: null, maxHeight: null, focus: false,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']], ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'hr', 'uploadfile']],
                ['view', ['fullscreen', 'codeview']],
                ['help', ['help']]
            ],
        });


        $.ajax({
            type: "POST",
            url: "/PageContent/gfhc",
            success: function (response) {

                $("#HTMLContent").summernote('code',  response);
            },
            error: function (data, textStatus, XMLHttpRequest) {

            }
        });

    });
</script>